### ISSUE TITLE
Pre-requisites

### ISSUE THREAD

**Issue by Th4tM0nk3y** [evbc/phase1#26]
Welche Voraussetzungen müssen gegeben sein, um dieses Projekt durch zu führen?
- Cluster?
- Applikationen/Container?
- Location? (Lokal/Server?)

**Comment by evbc** [comment]
Sind das Anweisungen? Woran erkenne ich das das Ticket fertig bearbeitet ist?

**Comment by JohannesBal** [comment]
Termin finden für Kunnden Workshop

**Comment by Th4tM0nk3y** [comment]
Bitte einmal Fragen beantworten @JohannesBal:
- Welchen Cluster nutzen wir?
- Welche Applikationen bzw Container nutzen wir?
- Wo hosten wir den Cluster?

Dient der Dokumentation von unserer Arbeit

**Comment by JohannesBal** [comment]
@Th4tM0nk3y 

13.2.23 13 - 16 Uhr Termin für Workshop mit dem Kunden
