### ISSUE TITLE
Installation des Helm Charts auf dem Cluster

### ISSUE THREAD

**Issue by ricket-son** [evbc/phase1#27]
## Requirements

- [ ] Cluster muss verfügbar sein
- [ ] Helm auf Host installiert haben

## Steps
- [ ] Verbindung zum Cluster aufbauen
- [ ] Helm Projekt erstellen / vorgefertigtes Projekt klonen
- [ ] Helm Chart installieren
- [ ] Chart Start überprüfen

**Comment by evbc** [comment]
Welcher Cluster?

**Comment by yk94x** [comment]
Welchen hast du dir rausgesucht?

**Comment by JohannesBal** [comment]
der kind cluster  wird verwendet.
