### ISSUE TITLE
Erstellung des Webfrontends

### ISSUE THREAD

**Issue by Iryn1234** [evbc/phase1#30]
Vorbedingung: DB Chart vorhanden und ready to use.
DOD:
1. Helmchart ist installierbar (Wie im READMIE spezifiziert.)
2. Adminer ist vom Browser aus aufrufbar

**Comment by evbc** [comment]
Hier gibt es eine Abhängigkeit die nicht erwähnt wird. Das Helm Chart hängt von einem anderen ab. Einem DB Chart das dem Adminer als backplane dient.

**Comment by evbc** [comment]
Pull request erstellt

**Comment by Iryn1234** [comment]
> Hier gibt es eine Abhängigkeit die nicht erwähnt wird. Das Helm Chart hängt von einem anderen ab. Einem DB Chart das dem Adminer als backplane dient.

Editiert
