### ISSUE TITLE
Test, Skalierbarkeit, Zuverlässigkeit

### ISSUE THREAD

**Issue by behnuryildiz** [evbc/phase1#34]
1. Teststufen

- [x] Komponententest
- [x] Integrationstest
- [x] Abnahmetest

2.  Skalierbarkeit anmessen

- [x] Lässt sich die Größe flexibel ändern?

3.  Das System ist dauerhaft stabil beziehungsweise beständig ? 

- Qualitätskriterien; Konsistenz, Fehlertoleranz und Genauigkeit.

**Comment by evbc** [comment]
![Bildschirm­foto 2023-02-10 um 15 12 06](https://user-images.githubusercontent.com/123601944/218112876-4f6dde6a-daae-4ee6-97e2-56a29ee75e16.png)

**Comment by evbc** [comment]
Ok, funktioniert. Kann dann wohl geschlossen werden...

**Comment by behnuryildiz** [comment]
perfekt! danke für deine Mithilfe! 👍
