### ISSUE TITLE
Credentials dürfen nicht in's Git

### ISSUE THREAD

**Issue by Th4tM0nk3y** [evbc/phase1#42]
https://github.com/evbc/phase1/pull/36 Bitte einmal anpassen, Credentials haben im Git nichts verloren!

**Comment by evbc** [comment]
![Bildschirm­foto 2023-02-10 um 15 18 29](https://user-images.githubusercontent.com/123601944/218114239-ae6247d0-3245-4b20-9d45-b6e7e7f34c45.png)

**Comment by Th4tM0nk3y** [comment]
Geht auch nicht um den Main Branch, ich habe im Issue den Pull Request verlinkt - Dort müssen die Credentials raus, bevor gemerget werden kann

**Comment by evbc** [comment]
Wozu dann das Ticket? Das ist doch dann Bestandteil des Reviews?

**Comment by Th4tM0nk3y** [comment]
Doppelt gemoppelt, sorry
