### ISSUE TITLE
Helm Charts

### ISSUE THREAD

**Issue by yk94x** [evbc/phase1#46]
Erstellen von Helm Charts

**Comment by evbc** [comment]
Das bräuchten wir etwas genauer. Was genau sollen die Charts enthalten? Wo ist das spezifiziert?

**Comment by 786tam** [comment]
Helm Charts benötigt Anweisungen , um zu wissen, wie ein Kubernetes  aufgebaut ist

**Comment by yk94x** [comment]
Wenn wir CRUD erstellen wollen, brauchen wir eine Chart.yaml datei, dort kommen die Metadaten rein, die verwendeten Tags sollten sein: Description, sources, maintainers, icon. Sollten wir dependencies enthalten, werden die in requirements.yaml spezifiziert. Dann natürlich jeweils in den templates, deployment, secrets. Wichtig ist es noch, die leerzeilen zu beachten...
